#!/bin/bash

while getopts ":d" opt; do
  case ${opt} in
    d) let justData=true;
      ;;
  esac
done
shift $((OPTIND -1))

dst="pi@${1:-192.168.1.39}"
port=${2:-22}

function killIt {
    ssh -p $port $dst "pid=\$(ps -ef | grep server.js | grep -v grep | grep -v sudo | cut -c10-15); test -n \"\$pid\" && sudo xargs kill -9 \$pid"
}

scp -r -P $port -r *.js package.json lib/ $dst:camera

if [ -z $justData ]; then
  killIt
  trap killIt EXIT
  ssh -p $port -t $dst "cd camera; sudo node server.js"
fi
