#!/bin/bash

BROKER="${BROKER:-http://localhost:5000}"
TOKENS="/var/broker/tokens"

# Simple utility to grant and revoke authorization tokens for the pan/tilt camera

function usage () {
    echo "usage: ptcam-auth <camera> list" >&2
    echo "       ptcam-auth <camera> <name>" >&2
    echo "       ptcam-auth <camera> grant <name>" >&2
    echo "       ptcam-auth <camera> revoke <name>" >&2
}

camera="${1}"

[ "$camera" = "--help" ] && usage && exit 1
[ ! -f ${TOKENS} ] && touch ${TOKENS}

cd $(dirname $0)

case "${2:-list}" in
list)
        [ -n ${camera} ] && grep " ${camera} " ${TOKENS} || cat ${TOKENS}
        ;;
grant)
        echo ${3:-guest}: ${camera} $(uuidgen) >> ${TOKENS}
        t=$(grep "${3:-guest}: ${camera} " ${TOKENS} | cut -d\  -f3)
        [ -n $t ] && echo "${BROKER}/camera/?id=${camera}&t=$t"
        ;;
revoke)
        egrep -v "^${3:-guest}: ${camera} " ${TOKENS} > ${TOKENS}.save
        mv ${TOKENS}.save ${TOKENS}
        ;;
*)
        t=$(grep "^${2:-guest}: ${camera} " ${TOKENS} | cut -d\  -f3)
        [ -n $t ] && echo "${BROKER}/camera/?id=${camera}&t=$t"
        ;;
esac

